### ISSUE TITLE
Disable add to cart button also

### ISSUE THREAD

**Issue by magejunkie** [dsasmita/magento2-hide-price-not-login#1]
Is it possible to disable add to cart button also.

**Comment by dsasmita** [comment]
Possible, just extend then button phtml

**Comment by magejunkie** [comment]
Can you please elaborate

**Comment by RustyIngles** [comment]
I'd like to know how to disable the add to cart button also please

**Comment by dsasmita** [comment]
@magejunkie @RustyIngles I have create one for prevent add to cart
https://github.com/dsasmita/magento2-preventtocart

**Comment by RustyIngles** [comment]
Excellent, thank you @dsasmita
